In [1]:
# math operations
# broadcasting

In [2]:
import numpy as np

In [3]:
np.empty((4,5))      # Return a new array with random values

array([[4.66786400e-310, 0.00000000e+000, 6.93096435e-310,
        6.93096435e-310, 6.93096432e-310],
       [6.93096432e-310, 6.93096338e-310, 6.93096424e-310,
        6.93096428e-310, 6.93096435e-310],
       [6.93096415e-310, 6.93096431e-310, 6.93096435e-310,
        6.93096427e-310, 6.93096338e-310],
       [6.93096436e-310, 6.93096344e-310, 6.93096410e-310,
        6.93096428e-310, 6.93096372e-310]])

In [4]:
np.eye(4)     #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
np.linspace(2, 4 , 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [6]:
np.logspace(2,4,20)    # calculating log of values which we get via linspace

array([  100.        ,   127.42749857,   162.37767392,   206.91380811,
         263.66508987,   335.98182863,   428.13323987,   545.55947812,
         695.19279618,   885.86679041,  1128.83789168,  1438.44988829,
        1832.98071083,  2335.72146909,  2976.35144163,  3792.69019073,
        4832.93023857,  6158.48211066,  7847.59970351, 10000.        ])

In [7]:
np.logspace(2,4,10,base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [8]:
arr = np.random.rand(3,4)      # 3*4 matrix is generated

In [9]:
arr

array([[0.28771696, 0.89059237, 0.54946054, 0.70695384],
       [0.38267598, 0.11392332, 0.10110919, 0.53569614],
       [0.94034245, 0.39161972, 0.59741804, 0.75556375]])

In [10]:
import pandas as pd

In [11]:
pd.DataFrame(arr)

0         1         2         3
0  0.287717  0.890592  0.549461  0.706954
1  0.382676  0.113923  0.101109  0.535696
2  0.940342  0.391620  0.597418  0.755564

In [12]:
np.random.randn(3,4)      # mean=0 standard_deviation=1   .....standard normal distribution

array([[-1.15926347, -0.82637854,  0.61251317,  1.15294726],
       [-2.11579092, -0.57001138, -1.01640084,  0.03412736],
       [ 0.26173153, -0.54174749, -0.73735321,  1.76392875]])

In [13]:
np.random.randint(1,50,(3,4))   #values are between 1 to 50

array([[26, 45, 49,  4],
       [ 9, 17, 32, 10],
       [43, 27, 17, 24]])

In [14]:
pd.DataFrame(np.random.randint(50,150,(13,14))).to_csv('test.csv')

In [15]:
arr1 = np.random.rand(4,3) 

In [16]:
arr1

array([[0.46451561, 0.94362637, 0.63826901],
       [0.91641587, 0.64151474, 0.84581565],
       [0.09406906, 0.14243622, 0.44114572],
       [0.63231379, 0.49875809, 0.93118012]])

In [17]:
# changing the dimensions of arr1, it should be of previous row* col size

In [18]:
arr1.reshape(6,2)
# arr.reshape(2,14)      # give error

array([[0.46451561, 0.94362637],
       [0.63826901, 0.91641587],
       [0.64151474, 0.84581565],
       [0.09406906, 0.14243622],
       [0.44114572, 0.63231379],
       [0.49875809, 0.93118012]])

In [19]:
arr2 = arr1.reshape(3,-143)    # negative value means understand urself

In [20]:
arr2

array([[0.46451561, 0.94362637, 0.63826901, 0.91641587],
       [0.64151474, 0.84581565, 0.09406906, 0.14243622],
       [0.44114572, 0.63231379, 0.49875809, 0.93118012]])

In [21]:
arr2[1:3,1]

array([0.84581565, 0.63231379])

In [22]:
arr3 = np.random.randint(1,150,(6,4))

In [23]:
arr3

array([[ 49, 141,  99,  95],
       [131,  74,  31,  13],
       [ 49,  80, 101,  31],
       [ 92, 126,  27,  99],
       [ 95,  41,  61,  65],
       [ 62,  53,  64,  71]])

In [24]:
# take data which is > 50

In [25]:
arr3 > 50

array([[False,  True,  True,  True],
       [ True,  True, False, False],
       [False,  True,  True, False],
       [ True,  True, False,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [26]:
arr3[arr3 > 50]

array([141,  99,  95, 131,  74,  80, 101,  92, 126,  99,  95,  61,  65,
        62,  53,  64,  71])

In [27]:
# extracting the data which is in between the metrix

In [28]:
arr3[2:4,[1,2]]

array([[ 80, 101],
       [126,  27]])

In [29]:
arr3

array([[ 49, 141,  99,  95],
       [131,  74,  31,  13],
       [ 49,  80, 101,  31],
       [ 92, 126,  27,  99],
       [ 95,  41,  61,  65],
       [ 62,  53,  64,  71]])

In [30]:
arr3[0][2] = 90

In [31]:
arr3

array([[ 49, 141,  90,  95],
       [131,  74,  31,  13],
       [ 49,  80, 101,  31],
       [ 92, 126,  27,  99],
       [ 95,  41,  61,  65],
       [ 62,  53,  64,  71]])

In [32]:
# math operations

In [60]:
arr4 = np.random.randint(1,4,(3,3))
arr5 = np.random.randint(1,4,(3,3))

In [61]:
arr4

array([[3, 2, 1],
       [1, 3, 1],
       [3, 3, 2]])

In [62]:
arr5

array([[1, 3, 2],
       [1, 1, 2],
       [3, 2, 2]])

In [63]:
arr4*arr5      #not a matrix mul

array([[3, 6, 2],
       [1, 3, 2],
       [9, 6, 4]])

In [64]:
arr4/arr5

array([[3.        , 0.66666667, 0.5       ],
       [1.        , 3.        , 0.5       ],
       [1.        , 1.5       , 1.        ]])

In [65]:
arr4+arr5

array([[4, 5, 3],
       [2, 4, 3],
       [6, 5, 4]])

In [66]:
arr4@arr5       # matrix mul

array([[ 8, 13, 12],
       [ 7,  8, 10],
       [12, 16, 16]])

In [67]:
arr4%arr5

array([[0, 2, 1],
       [0, 0, 1],
       [0, 1, 0]])

In [40]:
arr4/0

/tmp/ipykernel_1090/1674986024.py:1: RuntimeWarning: divide by zero encountered in divide
  arr4/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [41]:
arr4

array([[1, 1, 2],
       [1, 1, 3],
       [2, 3, 2]])

In [42]:
arr4 + 100

array([[101, 101, 102],
       [101, 101, 103],
       [102, 103, 102]])

In [68]:
arr4 ** arr5

array([[ 3,  8,  1],
       [ 1,  3,  1],
       [27,  9,  4]])

In [43]:
arr4 ** 2

array([[1, 1, 4],
       [1, 1, 9],
       [4, 9, 4]])

In [44]:
# broadcasting row wise

In [45]:
arr5 = np.zeros((4,4))

In [46]:
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
row = np.array([4,5,6,7])

In [48]:
row

array([4, 5, 6, 7])

In [49]:
arr5 + row

array([[4., 5., 6., 7.],
       [4., 5., 6., 7.],
       [4., 5., 6., 7.],
       [4., 5., 6., 7.]])

In [50]:
row.T    # 1d array can't be transposed

array([4, 5, 6, 7])

In [51]:
# broadcasting column wise

In [52]:
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
col = np.array([[4,5,6,7]])  # 2d array

In [54]:
col.T + arr5

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [55]:
arr4

array([[1, 1, 2],
       [1, 1, 3],
       [2, 3, 2]])

In [56]:
np.sqrt(arr4)

array([[1.        , 1.        , 1.41421356],
       [1.        , 1.        , 1.73205081],
       [1.41421356, 1.73205081, 1.41421356]])

In [57]:
np.exp(arr4)     # it is e power value (e is 2.7182)

array([[ 2.71828183,  2.71828183,  7.3890561 ],
       [ 2.71828183,  2.71828183, 20.08553692],
       [ 7.3890561 , 20.08553692,  7.3890561 ]])

In [58]:
np.log10(arr4)

array([[0.        , 0.        , 0.30103   ],
       [0.        , 0.        , 0.47712125],
       [0.30103   , 0.47712125, 0.30103   ]])