In [1]:
# shallow and deep copy
# making nd array using many ways
# data types

In [2]:
import numpy as np

In [3]:
# here we deal with arrays and metrix

In [4]:
l = [1,3,4,5]

In [5]:
arr = np.array(l)

In [6]:
arr

array([1, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
np.array([[8,2],[3,4]])

array([[8, 2],
       [3, 4]])

In [9]:
np.asarray(l)

array([1, 3, 4, 5])

In [10]:
a = [4,6,9]

In [11]:
np.asanyarray(a)

array([4, 6, 9])

In [12]:
b = np.matrix(l)

In [13]:
b

matrix([[1, 3, 4, 5]])

In [14]:
np.asanyarray(b)

matrix([[1, 3, 4, 5]])

In [15]:
new_arr = np.array(l)

In [16]:
new_arr

array([1, 3, 4, 5])

In [17]:
# shallow copy

In [18]:
c = new_arr     # c and new_arr are pointing to same thing

In [19]:
c

array([1, 3, 4, 5])

In [20]:
new_arr

array([1, 3, 4, 5])

In [21]:
c[0]

1

In [22]:
c[0] = 100

In [23]:
c

array([100,   3,   4,   5])

In [24]:
new_arr

array([100,   3,   4,   5])

In [25]:
# deep copy => allocates in new location

In [26]:
d = np.copy(new_arr)

In [27]:
d

array([100,   3,   4,   5])

In [28]:
new_arr

array([100,   3,   4,   5])

In [29]:
new_arr[1] = 400

In [30]:
new_arr

array([100, 400,   4,   5])

In [31]:
d

array([100,   3,   4,   5])

In [32]:
# making a 3*3 array having condition i==j 

In [33]:
np.fromfunction(lambda i, j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [34]:
#it is doing multiplication of indices

In [35]:
np.fromfunction(lambda i, j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [36]:
# creating array from iterables

In [37]:
iterable = (i*i for i in range(5))

In [38]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [39]:
np.fromstring('80 82 89 99', sep=' ')

array([80., 82., 89., 99.])

In [40]:
np.fromstring('8,2,9,99', sep=',')

array([ 8.,  2.,  9., 99.])

In [41]:
# data types

In [42]:
l = [3,5,7,9,11]

In [43]:
ar = np.array(l)

In [44]:
ar

array([ 3,  5,  7,  9, 11])

In [45]:
ar.ndim     #checking dimensions

1

In [46]:
ar.size

5

In [47]:
ar2 = np.array([[2,4,5,6],[5,6,7,8],[2,4,9,23]])

In [48]:
ar2

array([[ 2,  4,  5,  6],
       [ 5,  6,  7,  8],
       [ 2,  4,  9, 23]])

In [49]:
ar2.ndim 

2

In [50]:
ar2.size

12

In [51]:
ar

array([ 3,  5,  7,  9, 11])

In [52]:
ar2

array([[ 2,  4,  5,  6],
       [ 5,  6,  7,  8],
       [ 2,  4,  9, 23]])

In [53]:
ar.shape

(5,)

In [54]:
ar2.shape

(3, 4)

In [55]:
ar.dtype

dtype('int64')

In [56]:
ar2.dtype

dtype('int64')

In [57]:
ar3 = np.array([(1.4,45,55), (23,45,66)])       #as one is floating point number, it will make all as floating point

In [58]:
ar3     

array([[ 1.4, 45. , 55. ],
       [23. , 45. , 66. ]])

In [59]:
ar3.dtype

dtype('float64')

In [60]:
list(range(5))

[0, 1, 2, 3, 4]

In [61]:
# list(range(0.1,5))       # floating point is not possible here

In [62]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [63]:
list(np.arange(2.3,5.6,0.4))

[2.3,
 2.6999999999999997,
 3.0999999999999996,
 3.4999999999999996,
 3.8999999999999995,
 4.299999999999999,
 4.699999999999999,
 5.1,
 5.499999999999999]

In [64]:
# in given interval(1-5) it will produce particular data(here 10)

In [65]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [66]:
np.zeros(5)  #produce array having all values as 0

array([0., 0., 0., 0., 0.])

In [67]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [70]:
ar4 = np.zeros((3,4,2,3))

In [71]:
ar4.ndim

4

In [73]:
np.ones(4)

array([1., 1., 1., 1.])

In [76]:
on = np.ones((2,3,2))

In [77]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [78]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [79]:
on * 7

array([[[7., 7.],
        [7., 7.],
        [7., 7.]],

       [[7., 7.],
        [7., 7.],
        [7., 7.]]])