In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10, (3,4))

In [3]:
arr

array([[7, 5, 1, 2],
       [8, 9, 2, 1],
       [9, 6, 3, 3]])

In [4]:
arr.reshape(6,2)

array([[7, 5],
       [1, 2],
       [8, 9],
       [2, 1],
       [9, 6],
       [3, 3]])

In [5]:
arr.T

array([[7, 8, 9],
       [5, 9, 6],
       [1, 2, 3],
       [2, 1, 3]])

In [6]:
arr.flatten()

array([7, 5, 1, 2, 8, 9, 2, 1, 9, 6, 3, 3])

In [7]:
arr1 = np.array([5,6,7,8,9])

In [8]:
arr1.ndim

1

In [9]:
np.expand_dims(arr1,axis=0)   # it expands the dimension in row by 1

array([[5, 6, 7, 8, 9]])

In [10]:
np.expand_dims(arr1,axis=1)   # it expands the dimension by 1

array([[5],
       [6],
       [7],
       [8],
       [9]])

In [11]:
arr

array([[7, 5, 1, 2],
       [8, 9, 2, 1],
       [9, 6, 3, 3]])

In [12]:
np.squeeze(arr)    #works on size 1, refer info

array([[7, 5, 1, 2],
       [8, 9, 2, 1],
       [9, 6, 3, 3]])

In [13]:
arr2 = np.array([[1],[2],[3]])

In [14]:
arr2

array([[1],
       [2],
       [3]])

In [15]:
np.squeeze(arr2)

array([1, 2, 3])

In [16]:
arr1

array([5, 6, 7, 8, 9])

In [17]:
np.repeat(arr1,3)

array([5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9])

In [18]:
np.roll(arr1,shift=2)

array([8, 9, 5, 6, 7])

In [19]:
arr1

array([5, 6, 7, 8, 9])

In [20]:
np.diag(arr1)

array([[5, 0, 0, 0, 0],
       [0, 6, 0, 0, 0],
       [0, 0, 7, 0, 0],
       [0, 0, 0, 8, 0],
       [0, 0, 0, 0, 9]])

In [21]:
# binary operators

In [22]:
arr3 = np.random.randint(2,7,(3,4))

In [23]:
arr4 = np.random.randint(2,7,(3,4))

In [24]:
arr3

array([[3, 5, 5, 6],
       [6, 5, 5, 6],
       [4, 6, 6, 3]])

In [25]:
arr4

array([[2, 6, 2, 5],
       [4, 2, 5, 4],
       [3, 6, 6, 3]])

In [26]:
arr3 & arr4

array([[2, 4, 0, 4],
       [4, 0, 5, 4],
       [0, 6, 6, 3]])

In [27]:
~arr3         

array([[-4, -6, -6, -7],
       [-7, -6, -6, -7],
       [-5, -7, -7, -4]])

In [28]:
arr3 | arr4

array([[3, 7, 7, 7],
       [6, 7, 5, 6],
       [7, 6, 6, 3]])

In [29]:
arr3 > arr4

array([[ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True, False, False, False]])

In [30]:
# string functions

In [31]:
arr5 = np.array(['shri','kuresh'])

In [32]:
np.char.upper(arr5)

array(['SHRI', 'KURESH'], dtype='<U6')

In [34]:
np.char.title(arr5)

array(['Shri', 'Kuresh'], dtype='<U6')

In [35]:
np.char.capitalize(arr5)

array(['Shri', 'Kuresh'], dtype='<U6')

In [36]:
# mathematical functions

In [42]:
arr4

array([[2, 6, 2, 5],
       [4, 2, 5, 4],
       [3, 6, 6, 3]])

In [43]:
np.sin(arr4)

array([[ 0.90929743, -0.2794155 ,  0.90929743, -0.95892427],
       [-0.7568025 ,  0.90929743, -0.95892427, -0.7568025 ],
       [ 0.14112001, -0.2794155 , -0.2794155 ,  0.14112001]])

In [44]:
np.cos(arr4)

array([[-0.41614684,  0.96017029, -0.41614684,  0.28366219],
       [-0.65364362, -0.41614684,  0.28366219, -0.65364362],
       [-0.9899925 ,  0.96017029,  0.96017029, -0.9899925 ]])

In [45]:
np.tan(arr4)

array([[-2.18503986, -0.29100619, -2.18503986, -3.38051501],
       [ 1.15782128, -2.18503986, -3.38051501,  1.15782128],
       [-0.14254654, -0.29100619, -0.29100619, -0.14254654]])

In [46]:
np.tanh(arr4)

array([[0.96402758, 0.99998771, 0.96402758, 0.9999092 ],
       [0.9993293 , 0.96402758, 0.9999092 , 0.9993293 ],
       [0.99505475, 0.99998771, 0.99998771, 0.99505475]])

In [47]:
np.log10(arr4)

array([[0.30103   , 0.77815125, 0.30103   , 0.69897   ],
       [0.60205999, 0.30103   , 0.69897   , 0.60205999],
       [0.47712125, 0.77815125, 0.77815125, 0.47712125]])

In [48]:
np.sqrt(arr4)

array([[1.41421356, 2.44948974, 1.41421356, 2.23606798],
       [2.        , 1.41421356, 2.23606798, 2.        ],
       [1.73205081, 2.44948974, 2.44948974, 1.73205081]])

In [49]:
np.power(arr4,2)

array([[ 4, 36,  4, 25],
       [16,  4, 25, 16],
       [ 9, 36, 36,  9]])

In [50]:
np.mean(arr4)

4.0

In [52]:
np.std(arr4)

1.5275252316519468

In [53]:
np.var(arr4)

2.3333333333333335

In [54]:
np.min(arr4)

2