In [1]:
# sort, search, count functions

In [2]:
import numpy as np

In [3]:
arr = np.array([4,8,2,1,16,8])

In [4]:
arr

array([ 4,  8,  2,  1, 16,  8])

In [5]:
arr1 = np.sort(arr)

In [6]:
arr1

array([ 1,  2,  4,  8,  8, 16])

In [7]:
np.searchsorted(arr1,5)

3

In [8]:
arr2 = np.array([0,4,0,6,22,0,0,5])

In [9]:
np.count_nonzero(arr2)

4

In [10]:
arr

array([ 4,  8,  2,  1, 16,  8])

In [11]:
np.where(arr > 4)  # indices where values are > 4

(array([1, 4, 5]),)

In [12]:
np.extract(arr > 7,arr)

array([ 8, 16,  8])

In [13]:
arr.byteswap()

array([ 288230376151711744,  576460752303423488,  144115188075855872,
         72057594037927936, 1152921504606846976,  576460752303423488])

In [14]:
# copies and views

In [15]:
arr

array([ 4,  8,  2,  1, 16,  8])

In [16]:
a = np.copy(arr)      # deep copy

In [17]:
b = arr.view()         # shallow copy (b==arr)

In [18]:
b

array([ 4,  8,  2,  1, 16,  8])

In [19]:
arr

array([ 4,  8,  2,  1, 16,  8])

In [20]:
b[0] = 67

In [21]:
b

array([67,  8,  2,  1, 16,  8])

In [22]:
arr

array([67,  8,  2,  1, 16,  8])

In [23]:
a[0] = 99

In [24]:
a

array([99,  8,  2,  1, 16,  8])

In [25]:
arr

array([67,  8,  2,  1, 16,  8])

In [26]:
# matrix library

In [27]:
import numpy.matlib as nm

In [28]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [29]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
nm.eye(5)        # identity matrix

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [31]:
# linear algebra

In [53]:
arr3 = np.random.randint([[2,3], [4,5]])

In [54]:
arr4 = np.random.randint([[5,3], [2,5]])

In [55]:
arr3

array([[1, 1],
       [3, 2]])

In [56]:
arr4

array([[1, 0],
       [1, 3]])

In [57]:
np.dot(arr3,arr4)

array([[2, 3],
       [5, 6]])

In [58]:
arr3@arr4     # matrix mul

array([[2, 3],
       [5, 6]])